# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-07 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zpravy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateTimeField(verbose_name='Datum zveřejnění')),
                ('titulek', models.CharField(max_length=127, verbose_name='Titulek')),
                ('obsah', models.CharField(max_length=999, verbose_name='Obsah')),
                ('obrazek', models.FileField(blank=True, max_length=255, null=True, upload_to='images', verbose_name='Obrázek')),
            ],
            options={
                'verbose_name': 'Zpráva',
                'verbose_name_plural': 'Zprávy',
            },
        ),
    ]
