# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zpravy',
            name='datum',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Datum zveřejnění'),
        ),
        migrations.AlterField(
            model_name='zpravy',
            name='obsah',
            field=models.CharField(default='', max_length=999, verbose_name='Obsah'),
        ),
        migrations.AlterField(
            model_name='zpravy',
            name='titulek',
            field=models.CharField(default='', max_length=127, verbose_name='Titulek'),
        ),
    ]
